### PR TITLE
Introduce the Announcement wrapper component. 

### PR DESCRIPTION
**Pull request by peculiarity**
It can display announcements or skip the announcement and display the main view.
We can turn this off with a single component property or if we would like to have different setup for different environment then the property value can be set based on an `env` property ( do we need this right now? )

Another cool feature is that we can display the announcement once ( there is a flag set in the localStorage) or on each load ( the localStorage flag is ignored ) 

Another cool feature could be to store for each announcement an id so that we can chain announcements but that can be done later.

### CODE REVIEW

**Comment by maciejka** [comment]
Name of property in local storage should be configurable as we might have various announcements.

**Comment by peculiarity** [comment]
> Name of property in local storage should be configurable as we might have various announcements.

Actually I've thought about it  and that's why I mentioned `id`'s. With the generated ID's we can have a chain of announcement. First announcement might be `once` and second `always` and it will work but for now if it's the opposite way it won't work since the first will set the flag `on` and the second won't be displayed.

 I will extend it right after I configure solc on my compute so that I can run `oasis-local-node` and verify e2e tests.

**Comment by krzkaczor** [comment]
What do we do with e2e tests @peculiarity? i would switch it off and remove clicking button in tests.

**Comment by peculiarity** [comment]
@krzkaczor that has been already done. The failing e2e test is not due to that case.

**Pull request merged**
